const { Stack } = require("./stacks")
const Queue = require("./queues")

let stack = new Stack()
stack.push('ok')
stack.push('ok2')
stack.push('ok3')
stack.pop()
console.log(stack)

let queue = new Queue()
queue.enqueue('Joy')
queue.enqueue('Math')
queue.enqueue('Roger')
console.log(queue)
queue.dequeue()
console.log(queue)
